//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Contexto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Prod.SNE.Datos.Modelo;
    
    public partial class ClimaOrganizacionalDbContext : DbContext
    {
        public ClimaOrganizacionalDbContext()
            : base("name=ClimaOrganizacionalDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cat_categoria> cat_categoria { get; set; }
        public virtual DbSet<cat_configuracion_inicial> cat_configuracion_inicial { get; set; }
        public virtual DbSet<cat_sub_categoria> cat_sub_categoria { get; set; }
        public virtual DbSet<dat_encuesta_agradecimiento> dat_encuesta_agradecimiento { get; set; }
        public virtual DbSet<dat_encuesta_bienvenida> dat_encuesta_bienvenida { get; set; }
        public virtual DbSet<dat_encuesta_encuestado> dat_encuesta_encuestado { get; set; }
        public virtual DbSet<dat_respuesta> dat_respuesta { get; set; }
        public virtual DbSet<dat_respuesta_pregunta> dat_respuesta_pregunta { get; set; }
        public virtual DbSet<vw_aplicacion> vw_aplicacion { get; set; }
        public virtual DbSet<vw_dependencia> vw_dependencia { get; set; }
        public virtual DbSet<vw_persona> vw_persona { get; set; }
        public virtual DbSet<vw_regimen> vw_regimen { get; set; }
        public virtual DbSet<vw_rol> vw_rol { get; set; }
        public virtual DbSet<vw_trabajador> vw_trabajador { get; set; }
        public virtual DbSet<cat_estado_encuesta> cat_estado_encuesta { get; set; }
        public virtual DbSet<cat_estado_respuesta> cat_estado_respuesta { get; set; }
        public virtual DbSet<cat_sexos> cat_sexos { get; set; }
        public virtual DbSet<cat_tipo_maestro_institucional> cat_tipo_maestro_institucional { get; set; }
        public virtual DbSet<cat_tipo_pregunta> cat_tipo_pregunta { get; set; }
        public virtual DbSet<cat_archivo_tipo_archivo> cat_archivo_tipo_archivo { get; set; }
        public virtual DbSet<cat_tipo_encuesta> cat_tipo_encuesta { get; set; }
        public virtual DbSet<cat_estado_administrado> cat_estado_administrado { get; set; }
        public virtual DbSet<dat_encuesta_administrado> dat_encuesta_administrado { get; set; }
        public virtual DbSet<dat_encuesta_seccion> dat_encuesta_seccion { get; set; }
        public virtual DbSet<cat_tipo_fecha> cat_tipo_fecha { get; set; }
        public virtual DbSet<dat_encuesta_notificacion> dat_encuesta_notificacion { get; set; }
        public virtual DbSet<cat_dirigido_notificacion> cat_dirigido_notificacion { get; set; }
        public virtual DbSet<cat_categoria_extranet> cat_categoria_extranet { get; set; }
        public virtual DbSet<cat_sub_categoria_extranet> cat_sub_categoria_extranet { get; set; }
        public virtual DbSet<vw_departamento> vw_departamento { get; set; }
        public virtual DbSet<vw_distrito> vw_distrito { get; set; }
        public virtual DbSet<vw_provincia> vw_provincia { get; set; }
        public virtual DbSet<cat_tipo_archivo> cat_tipo_archivo { get; set; }
        public virtual DbSet<dat_encuesta> dat_encuesta { get; set; }
        public virtual DbSet<dat_encuesta_pregunta> dat_encuesta_pregunta { get; set; }
        public virtual DbSet<vw_usuario_rol_intranet> vw_usuario_rol_intranet { get; set; }
    }
}
