//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("CAT_CONFIGURACION_INICIAL", Schema = "dbo")]
    
    public partial class cat_configuracion_inicial
    {
    	[Key()]	
    	public int id_configuracion { get; set; }
    	public string texto_bienvenida { get; set; }
    	public string iden_audio_fondo { get; set; }
    	public int id_tipo_archivo { get; set; }
    	public string url_video { get; set; }
    	public string iden_imagen { get; set; }
    	public bool es_eliminado { get; set; }
    	public System.DateTime fecha_creacion { get; set; }
    	public string usuario_creacion { get; set; }
    	public Nullable<System.DateTime> fecha_modificacion { get; set; }
    	public string usuario_modificacion { get; set; }
    	public string ip_creacion { get; set; }
    	public string ip_modificacion { get; set; }
    	public int id_tipo_encuesta { get; set; }
    
        public virtual cat_tipo_encuesta cat_tipo_encuesta { get; set; }
    }
}
