//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("CAT_ESTADO_ENCUESTA", Schema = "dbo")]
    
    public partial class cat_estado_encuesta
    {
        
        public cat_estado_encuesta()
        {
            this.dat_encuesta = new HashSet<dat_encuesta>();
        }
    
    	[Key()]	
    	public int id { get; set; }
    	public string nombre { get; set; }
    	public Nullable<bool> es_eliminado { get; set; }
    
        
        public virtual ICollection<dat_encuesta> dat_encuesta { get; set; }
    }
}
