//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("CAT_ESTADO_ADMINISTRADO", Schema = "dbo")]
    
    public partial class cat_estado_administrado
    {
        
        public cat_estado_administrado()
        {
            this.dat_encuesta_administrado = new HashSet<dat_encuesta_administrado>();
        }
    
    	[Key()]	
    	public int id_estado_administrado { get; set; }
    	public string nombre { get; set; }
    	public bool es_eliminado { get; set; }
    
        
        public virtual ICollection<dat_encuesta_administrado> dat_encuesta_administrado { get; set; }
    }
}
