//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("CAT_TIPO_ARCHIVO", Schema = "dbo")]
    
    public partial class cat_tipo_archivo
    {
        
        public cat_tipo_archivo()
        {
            this.dat_encuesta_agradecimiento = new HashSet<dat_encuesta_agradecimiento>();
            this.dat_encuesta_pregunta = new HashSet<dat_encuesta_pregunta>();
        }
    
    	[Key()]	
    	public int id { get; set; }
    	public string nombre { get; set; }
    	public Nullable<bool> es_eliminado { get; set; }
    
        
        public virtual ICollection<dat_encuesta_agradecimiento> dat_encuesta_agradecimiento { get; set; }
        
        public virtual ICollection<dat_encuesta_pregunta> dat_encuesta_pregunta { get; set; }
    }
}
