//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("DAT_ENCUESTA", Schema = "dbo")]
    
    public partial class dat_encuesta
    {
        
        public dat_encuesta()
        {
            this.dat_encuesta_bienvenida = new HashSet<dat_encuesta_bienvenida>();
            this.dat_encuesta_agradecimiento = new HashSet<dat_encuesta_agradecimiento>();
            this.dat_encuesta_encuestado = new HashSet<dat_encuesta_encuestado>();
            this.dat_encuesta_pregunta = new HashSet<dat_encuesta_pregunta>();
            this.dat_respuesta = new HashSet<dat_respuesta>();
            this.dat_encuesta_administrado = new HashSet<dat_encuesta_administrado>();
            this.dat_encuesta_seccion = new HashSet<dat_encuesta_seccion>();
            this.dat_encuesta_notificacion = new HashSet<dat_encuesta_notificacion>();
        }
    
    	[Key()]	
    	public int id_encuesta { get; set; }
    	public int id_dependendia { get; set; }
    	public string titulo { get; set; }
    	public string encabezado { get; set; }
    	public string objetivo { get; set; }
    	public string descripcion { get; set; }
    	public System.DateTime fecha_inicio { get; set; }
    	public System.DateTime fecha_fin { get; set; }
    	public int tiempo_estimado { get; set; }
    	public bool es_anonima { get; set; }
    	public bool es_todos { get; set; }
    	public string iden_imagen_presentacion { get; set; }
    	public string mensaje_corto_presentacion { get; set; }
    	public int id_estado { get; set; }
    	public bool es_eliminado { get; set; }
    	public System.DateTime fecha_creacion { get; set; }
    	public string usuario_creacion { get; set; }
    	public Nullable<System.DateTime> fecha_modificacion { get; set; }
    	public string usuario_modificacion { get; set; }
    	public string mensaje_es_anonima { get; set; }
    	public Nullable<System.DateTime> fecha_publicacion { get; set; }
    	public string iden_pdf_resultados { get; set; }
    	public Nullable<System.DateTime> fecha_resultados { get; set; }
    	public string nro_informe { get; set; }
    	public string iden_pdf_resultados_completo { get; set; }
    	public string ip_creacion { get; set; }
    	public string ip_modificacion { get; set; }
    	public int id_tipo_encuesta { get; set; }
    	public bool es_con_seccion_pregunta { get; set; }
    	public bool es_autorizado_datos { get; set; }    
        
        public virtual ICollection<dat_encuesta_bienvenida> dat_encuesta_bienvenida { get; set; }
        
        public virtual ICollection<dat_encuesta_agradecimiento> dat_encuesta_agradecimiento { get; set; }
        
        public virtual ICollection<dat_encuesta_encuestado> dat_encuesta_encuestado { get; set; }
        
        public virtual ICollection<dat_encuesta_pregunta> dat_encuesta_pregunta { get; set; }
        
        public virtual ICollection<dat_respuesta> dat_respuesta { get; set; }
        
        public virtual ICollection<dat_encuesta_administrado> dat_encuesta_administrado { get; set; }
        
        public virtual ICollection<dat_encuesta_seccion> dat_encuesta_seccion { get; set; }
        
        public virtual ICollection<dat_encuesta_notificacion> dat_encuesta_notificacion { get; set; }
    }
}
