//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("DAT_ENCUESTA_ADMINISTRADO", Schema = "dbo")]
    
    public partial class dat_encuesta_administrado
    {
    	[Key()]	
    	public int id_encuesta_administrado { get; set; }
    	public int id_encuesta { get; set; }
    	public int id_estado_administrado { get; set; }
    	public Nullable<System.DateTime> fecha_resuelto { get; set; }
    	public System.DateTime fecha_creacion { get; set; }
    	public string usuario_creacion { get; set; }
    	public Nullable<System.DateTime> fecha_modificacion { get; set; }
    	public string usuario_modificacion { get; set; }
    	public bool es_eliminado { get; set; }
    	public string ruc_administrado { get; set; }
    
        public virtual cat_estado_administrado cat_estado_administrado { get; set; }
        public virtual dat_encuesta dat_encuesta { get; set; }
    }
}
