//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("DAT_ENCUESTA_PREGUNTA", Schema = "dbo")]
    
    public partial class dat_encuesta_pregunta
    {
        
        public dat_encuesta_pregunta()
        {
            this.dat_respuesta_pregunta = new HashSet<dat_respuesta_pregunta>();
        }
    
    	[Key()]	
    	public int id_pregunta { get; set; }
    	public int id_encuesta { get; set; }
    	public string pregunta { get; set; }
    	public bool es_obligatorio { get; set; }
    	public int id_tipo_pregunta { get; set; }
    	public Nullable<int> id_categoria { get; set; }
    	public Nullable<int> id_sub_categoria { get; set; }
    	public string descripcion { get; set; }
    	public Nullable<int> id_tipo_archivo { get; set; }
    	public string iden_imagen { get; set; }
    	public string url_video { get; set; }
    	public string json_alternativas { get; set; }
    	public bool es_eliminado { get; set; }
    	public System.DateTime fecha_creacion { get; set; }
    	public string usuario_creacion { get; set; }
    	public Nullable<System.DateTime> fecha_modificacion { get; set; }
    	public string usuario_modificacion { get; set; }
    	public Nullable<bool> por_defecto { get; set; }
    	public Nullable<bool> es_condicional { get; set; }
    	public Nullable<bool> es_condicionada { get; set; }
    	public Nullable<int> id_pregunta_condicional { get; set; }
    	public string json_respuesta_condicional { get; set; }
    	public string json_archivo_tipo_archivo { get; set; }
    	public bool es_agregar_pregunta { get; set; }
    	public Nullable<int> orden { get; set; }
    	public bool es_finaliza_encuesta { get; set; }
    	public Nullable<int> id_encuesta_seccion { get; set; }
    	public string json_tipo_fecha { get; set; }
    
        public virtual cat_sub_categoria cat_sub_categoria { get; set; }
        public virtual dat_encuesta dat_encuesta { get; set; }
        public virtual cat_categoria cat_categoria { get; set; }
        
        public virtual ICollection<dat_respuesta_pregunta> dat_respuesta_pregunta { get; set; }
    }
}
