//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("DAT_ENCUESTA_AGRADECIMIENTO", Schema = "dbo")]
    
    public partial class dat_encuesta_agradecimiento
    {
    	[Key()]	
    	public int id_encuesta_agradecimiento { get; set; }
    	public int id_encuesta { get; set; }
    	public string mensaje_agradecimiento { get; set; }
    	public string iden_audio { get; set; }
    	public Nullable<int> id_tipo_archivo { get; set; }
    	public string iden_imagen { get; set; }
    	public string url_video { get; set; }
    	public bool es_eliminado { get; set; }
    	public System.DateTime fecha_creacion { get; set; }
    	public string usuario_creacion { get; set; }
    	public Nullable<System.DateTime> fecha_modificacion { get; set; }
    	public string usuario_modificacion { get; set; }
    	public Nullable<bool> es_activar_audio { get; set; }
    
        public virtual dat_encuesta dat_encuesta { get; set; }
        public virtual cat_tipo_archivo cat_tipo_archivo { get; set; }
    }
}
