//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("vw_dependencia", Schema = "dbo")]
    
    public partial class vw_dependencia
    {
    	[Key()]	
    	public int CODIGO_DEPENDENCIA { get; set; }
    	public string DEPENDENCIA { get; set; }
    	public string PISO { get; set; }
    	public string SIGLAS { get; set; }
    	public Nullable<System.DateTime> AUDIT_MOD { get; set; }
    	public Nullable<System.DateTime> AUDIT_CREA { get; set; }
    	public string CONDICION { get; set; }
    	public string DIRECTO { get; set; }
    	public string ANEXO { get; set; }
    	public string SECCION { get; set; }
    	public string CENTRAL { get; set; }
    	public string EMAIL { get; set; }
    	public string FAX { get; set; }
    	public string EQUIVALENCIA { get; set; }
    	public Nullable<int> PRIORIDAD { get; set; }
    	public Nullable<int> TIPO_DEPENDENCIA { get; set; }
    	public Nullable<int> CODDEP_PUB { get; set; }
    	public string PUBLICADO_WEB { get; set; }
    	public string USUARIO_CREACION { get; set; }
    	public string USUARIO_MODIFICACION { get; set; }
    	public Nullable<int> CODDEP_RESPONSABLE { get; set; }
    	public Nullable<int> ID_TIPO_DEPENDENCIA { get; set; }
    	public string PUBLICADO_EXTRANET { get; set; }
    	public Nullable<int> CODDEP_PRINCIPAL { get; set; }
    	public Nullable<bool> ES_DEPGENERAL { get; set; }
    	public string RUC_ENTIDAD { get; set; }
    }
}
