//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("vw_persona", Schema = "dbo")]
    
    public partial class vw_persona
    {
    	[Key()]	
    	public int ID { get; set; }
    	public int ID_SECTOR { get; set; }
    	public int ID_TIPO_PERSONA { get; set; }
    	public string CODIGO_DEPARTAMENTO { get; set; }
    	public string CODIGO_PROVINCIA { get; set; }
    	public string CODIGO_DISTRITO { get; set; }
    	public int ID_TIPO_IDENTIFICACION { get; set; }
    	public string RUBRO { get; set; }
    	public string RAZON_SOCIAL { get; set; }
    	public string NOMBRES { get; set; }
    	public string APELLIDOS { get; set; }
    	public string NRO_DOCUMENTO { get; set; }
    	public string DIRECCION { get; set; }
    	public string TELEFONO { get; set; }
    	public string FAX { get; set; }
    	public string EMAIL { get; set; }
    	public System.DateTime AUDIT_MOD { get; set; }
    	public string REPRESENTANTE_LEGAL { get; set; }
    	public string NRO_DOCUMENTO_REPRESENTANTE { get; set; }
    	public Nullable<int> ID_TIPO_IDENTIFICACION_REP_LEG { get; set; }
    	public Nullable<int> CODIGO_PUERTO { get; set; }
    	public string FLAG { get; set; }
    	public string usuario { get; set; }
    	public string OBSERVACIONES { get; set; }
    	public string CELULAR { get; set; }
    	public Nullable<int> ID_AURA { get; set; }
    	public string FLAG_OEC { get; set; }
    	public Nullable<int> ID_TIPO_ORGANIZACION { get; set; }
    	public string NRO_DOCPERNATURAL { get; set; }
    	public string USUARIO_MOD { get; set; }
    	public Nullable<System.DateTime> FECHA_MOD { get; set; }
    	public string COD_GENERO { get; set; }
    	public Nullable<bool> NO_TIENE_RUC { get; set; }
    }
}
