//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("vw_rol", Schema = "dbo")]
    
    public partial class vw_rol
    {
    	[Key()]	
    	public int id_rol { get; set; }
    	public int id_aplicacion { get; set; }
    	public string nombre { get; set; }
    	public string tipo_rol { get; set; }
    	public bool estado { get; set; }
    	public string usuario_registro { get; set; }
    	public System.DateTime fecha_registro { get; set; }
    	public string usuario_modificacion { get; set; }
    	public System.DateTime fecha_modificacion { get; set; }
    }
}
