//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prod.SNE.Datos.Modelo
{
	using System.ComponentModel.DataAnnotations;
	using System.ComponentModel.DataAnnotations.Schema;
    using System;
    using System.Collections.Generic;
    
    [Table("vw_usuario_rol_intranet", Schema = "dbo")]
    
    public partial class vw_usuario_rol_intranet
    {
    	public int codigo_trabajador { get; set; }
    	[Key()]	
    	public int id_rol { get; set; }
    	public string nombre { get; set; }
    }
}
